# Generated by Django 4.2 on 2023-04-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Hi there, I am using friend-share'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
