# Generated by Django 4.2 on 2023-04-29 20:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sended_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
